name: Snyk Serverless Framework Snyk IaC Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test and build
    environment: snyk-npm
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Setup Snyk
      run: |
        npm install snyk -g
        npm install snyk-to-html -g
        snyk auth ${{secrets.SNYK_AUTH}}
    - name: Setup Serverless
      run: |
        npm install -g serverless
    - name: Serverless test # Remove || true to fail on build, output in CLI
      run: |
        cd iac/aws-node
        serverless package --package serverless-artifacts
        cd ../..
        snyk iac test || true 
    #- name: Serverless test # Remove || true to fail on build, output in json file
    #  run: |
    #    cd iac/aws-node
    #    serverless package --package serverless-artifacts
    #    cd ../..
    #    snyk iac test || true > results.json
